name: 'Install PHP and Composer dependencies'
author: sanmai
description: 'Installs chosen PHP version, extensions, tools, and Composer dependencies from composer.json'
inputs:
  php-version:
    description: 'Install this PHP version.'
    required: true
  extensions:
    description: 'Setup selected PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage: 
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
  composer-version:
    description: 'Composer version to use.'
    default: 'v2'
    required: true
  composer-flags:
    description: 'Flags to pass to Composer when installing dependencies.'
    required: false


runs:
  using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          coverage: ${{ inputs.coverage }}
          tools: composer:${{ inputs.composer-version }} ${{ inputs.tools }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: composer-${{ inputs.php-version }}-${{ inputs.composer-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-${{ inputs.composer-version }}-
            composer-${{ matrix.php-version }}-
            composer-

      - name: Validate composer.json
        run: |
          composer validate --no-check-publish --no-check-lock

      - name: Install dependencies
        run: |
          composer update --no-interaction --no-progress ${{ inputs.composer-flags }}

